javascript:(
	function(){
		g="http://www.google.com/search?hl=en&";
		u=document.URL;
		s=u.indexOf("&q=")+1;
		if(s==0){s=u.indexOf("q=")};
		e=u.indexOf("&",s);
		if(e==-1){e=u.search(/$/)};
		location.href=g+u.slice(s,e);
	}
)
();
